version: '2'
services:
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    restart: always
    network_mode: host
  wingnut:
    image: quay.io/kringen/wingnut:latest
    container_name: wingnut
    hostname: wingnut
    environment:
    - RABBIT_URL=amqp://guest:guest@127.0.0.1:5672
    restart: always
    depends_on:
      - rabbitmq
    network_mode: host
  api:
    image: quay.io/kringen/wingnut-api:latest
    container_name: api
    hostname: api
    ports:
    - 8080:8080
    environment:
    - RABBIT_URL=amqp://guest:guest@127.0.0.1:5672
    restart: always
    depends_on:
      - rabbitmq
    network_mode: host
